server:
#  port: 9999
  port: 9898

spring:
  # 热部署
#  devtools:
#    restart:
#      enabled: true
  # 模板引擎缓存
  thymeleaf:
#    cache: false
    cache: true
  # DB configuration
  datasource:
    url: jdbc:mysql://localhost:3306/rob_artifact?autoCommit=false&useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    pool-prepared-statements: true
  # REDIS configuration
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 3600

# MyBatis configuration
mybatis:
  mapper-locations: classpath:META-INF/mybatis/*.xml

constant:
  # 本地系统验证码开关
  authCodeEnable: false
#  authCodeEnable: true
  # 抢票任务重启开关
#  taskRunnerEnable: false
  taskRunnerEnable: true
  # ocr语言训练库路径
#  tessdataPath: "tessdata"
  tessdataPath: "/home/llz/web/robArtifact/tessdata/"
  # 人工验证图片训练库路径
  codeImagePath: "O:\\图片\\12306\\图库\\"
